### ISSUE TITLE
search improvements needed

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/react#43]
be able to search for multiple terms (using "or" instead of "and") eg

Meeting: Attitude Adjustment
Location: Denny's Restaurant

Searching for "attitude denny" should turn this up

**Comment by FlipperPA** [comment]
What do you think about just swapping out pipes for commas on the current behavior? Where the comma/pipe acts as an "or"? We could just do a straightforward regex to convert commas to pipes and remove any spaces after commas. The pipe character is just a hard one to explain, especially on mobile ("It looks like a lowercase "L"!).

That would allow users to search for "west chester, paoli, malvern, devon" - four adjacent towns - all in one search: https://www.aasepia.org/?day=any&search=devon%7Cwest%20chester%7Cmalvern%7Cpaoli

The issue I'm running into with the "attitude denny" behavior would be that a search for "center city west" brings up meetings for "center city east" and "west chester".

**Comment by joshreisner** [comment]
I don't love the pipes idea because I don't want to implement something that needs training.

I think perhaps to accommodate your use case a second enhancement is needed after this one which is to use quotes around exact search phrases. That's not going to be something people use much, but at least it's also how Google works.

So in this case `center city west` would return all the ones containing any of those words, while `"center city west"` would only return matches with that exact sequence.

I do see that it's a slightly different solution than an AND vs OR search.

Another possibility for this use case, implementing search-as-you-type suggestions for regions, times, and types. So that if a region matched what you were typing, a 'quick search' button would appear, offering to filter by that term as if you'd used the region filter dropdown.

**Comment by FlipperPA** [comment]
A JavaScript work in progress for quoted identifier support. Putting it here until I have a chance to work on this further:

```javascript
var search_string = '"west chester" malvern devon "center city west"';
var terms = [];
var exp = /"(.*?)"/g;
// Grab any quoted strings, add them to terms, and delete from source string
for(var match=exp.exec(search_string); match!=null; match=exp.exec(search_string)) {
  search_string = search_string.replace(match[0], '');
  terms.push(match[0].replace(/"/g, ''));
}
// Add any non-quoted strings remaining to the terms
terms = terms.concat(search_string.match(/[^ ]+/g));
terms_string = terms.join('|');
// The array of terms
console.log(terms);
// What to pass to ReactJS search
console.log(terms_string);
```

**Comment by FlipperPA** [comment]
Slight change; only run the regex code if there's actually a double-quote in the string:

```javascript
var search_string = '"west chester" malvern devon "center city west"';

if search_string.includes('"') {
  var terms = [];
  var exp = /"(.*?)"/g;
  // Grab any quoted strings, add them to terms, and delete from source string
  for(var match=exp.exec(search_string); match!=null; match=exp.exec(search_string)) {
    search_string = search_string.replace(match[0], '');
    terms.push(match[0].replace(/"/g, ''));
  }
  // Add any non-quoted strings remaining to the terms
  terms = terms.concat(search_string.match(/[^ ]+/g));
  terms_string = terms.join('|');
  // The array of terms
  console.log(terms);
  // What to pass to ReactJS search
  console.log(terms_string);
} else {
  console.log(search_string);
}
```

**Comment by FlipperPA** [comment]
This should do the trick:

```javascript
function processSearch(search_string) {
  var terms = [];
  // Parse out any quoted strings
  if (search_string.includes('"')) {
    var exp = /"(.*?)"/g;
    // Grab any quoted strings, add them to terms, and delete from source string
    for (var match = exp.exec(search_string); match != null; match = exp.exec(search_string)) {
      search_string = search_string.replace(match[0], '');
      terms.push(match[0].replace(/"/g, ''));
    }
  }

  // Add any non-quoted strings remaining to the terms
  terms = terms.concat(search_string.match(/[^ ]+/g));

  // Return the the pipe delimited search string
  return terms.join('|');
}

console.log(processSearch('"west chester" malvern devon "center city west"'))
console.log(processSearch('attitude denny'))
```
