### ISSUE TITLE
Zoom icons (+/-) missing from MapBox components

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#45]
The CSS assets for MapBox components are included here:
https://github.com/code4recovery/react/blob/master/src/style.scss#L11

However, there appears to be a known issue with this not including the proper zoom icons:
https://stackoverflow.com/questions/41153811/mapbox-navigation-control-zoom-in-and-out

Using a tip from the first answer, I've worked around this by explicitly including the newer CSS:
https://github.com/code4recovery/wagtail-meeting-guide/commit/7e2cff2646bb1c35c4a880ab7a4e6b3dd4fa38e8

I *think* we could fix this by included the zoom in / zoom out CSS at the bottom of `style.scss` to override the CSS from the MapBox package installed by `npm install`; what do you think, @joshreisner?

**Comment by joshreisner** [comment]
Weird, I'm seeing them in `master` in Mac browsers, what are you using?

<img width="68" alt="Screen Shot 2019-12-30 at 9 35 30 AM" src="https://user-images.githubusercontent.com/1551689/71593156-c2121b80-2ae7-11ea-9e02-9a3302b5c721.png">

**Comment by joshreisner** [comment]
Hey @FlipperPA I see the +/- on this page: https://react.meetingguide.org/?view=map

Also here: https://www.aasepia.org/?meeting=meeting-1937-macdade-boulevard-woodlyn-pa-19094-usa-6-000000

Are you not?

**Comment by FlipperPA** [comment]
Hey @joshreisner - they're appearing because of a workaround I put in here: https://github.com/code4recovery/wagtail-meeting-guide/blob/master/meeting_guide/templates/meeting_guide/tags/meeting_guide.html#L3 It looks like this is an up-stream problem with the mapbox widget.

Also, any ideas why the + / - and drag aren't working on this map? https://www.aasepia.org/?view=map

I haven't had a chance to look yet, but thought you might know off the top of your head.

**Comment by joshreisner** [comment]
@FlipperPA but you can see them at the other link right? That would not be with your fix.

Zoom I don't think was ever implemented.

**Comment by FlipperPA** [comment]
@joshreisner You are correct - that must've been for the meeting detail view. Sorry about that!

However, if you look at them at AASEPIA or here: https://react.meetingguide.org/?view=map

- I see the zoom icons at laptop width, but they don't do anything when clicked. (Chrome & Firefox)
- At phone width, the zoom icons both disappear (Chrome, Firefox, & Safari, iPhone)

I'll open a new issue, if that's okay, since this can be reproduced across both of our sites. It isn't burning level importance or anything. :)
