### ISSUE TITLE
Fix Back Button Behavior on Meeting Detail View

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#47]
People are having trouble finding the "Meetings" link to return to the search after going into a meeting detail view.

**Comment by joshreisner** [comment]
<img width="964" alt="Screen Shot 2020-01-22 at 9 24 36 AM" src="https://user-images.githubusercontent.com/1551689/72917622-06649600-3cf9-11ea-95d4-cfd0da76466c.png">

This is the plugin's old behavior, I think this would be my preference on how to handle it.

The other obvious option would be to have a "back to meetings" button above the "directions" button but my sense is having two visually smilar buttons isn't such a great design choice.

The only problem is we make the "title" element optional in settings, so if you opt out of it, would you not be able to get back?

**Comment by FlipperPA** [comment]
Thanks @joshreisner, I think mimicking the old behavior makes sense. We've had a bunch of people calmly and politely (*cough*) indicate that they were having problems figuring out how to get back to the list.

Do we show the "> Back to Meetings" link regardless of the title setting?

**Comment by joshreisner** [comment]
@FlipperPA one other aspect to this issue that I just noticed: apparently using the back button to go back does not work. I think that's probably an easy fix but should be a top priority.

**Comment by joshreisner** [comment]
Well, I've looked at it a bit and it's not as simple as I'd hoped. I thought we might be able to use `window.onpopstate` to detect back button presses and rerun `getQueryString`. This works with a single back button press, but doesn't seem to work beyond that and doesn't allow then going forward again. Some more work is needed.

**Comment by FlipperPA** [comment]
A PR is in for the link (https://github.com/code4recovery/react/pull/49) so I'm going to rename the issue.
