### ISSUE TITLE
Zooming / Panning Stuck on Main Map

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#48]
While viewing the main map screen at either of these URLs:

- https://react.meetingguide.org/?view=map
- https://www.aasepia.org/?view=map

We should decide on a map behavior:

- I see the zoom icons at laptop width, but they don't do anything when clicked. (Chrome & Firefox)
- At laptop width, the cursor changes to the "draggable" hand, but the map is not draggable
- At phone width, the zoom icons both disappear (Chrome, Firefox, & Safari, iPhone)

My preference would be to re-create the current behavior with zoom and drag from TSML: https://aasanjose.org/meetings?tsml-view=map

**Comment by FlipperPA** [comment]
@joshreisner Taking an attempt at this here: https://github.com/code4recovery/react/commit/f09d15d4a9a80cc6770abd2ed2b7d233fae49fc4

**Comment by joshreisner** [comment]
Hey @FlipperPA users don't want to / should not see the zoom control on a mobile view -- it's not done in any app. They just use their fingers. It's necessary on desktop though.

If you wanted to modify that on aasepia you'd be welcome to, it's handled in CSS on line 74 of style.css.

Zooming / panning on the main map is a legit issue, if it's ok I'm going to rename this issue name to reflect that. It has to do with the `updateViewport` method in `map.jsx` and some buggy behavior. It's not fully intuitive how to set the initial map bounds around a cluster of points, that's what Uber's mercator projection library is doing. I suspect that's getting locked somehow.

**Comment by FlipperPA** [comment]
Ha, of course the zoom icons disappear on mobile... brain fart! :)

There may be an indicator in the JS console on why it isn’t working on the main map. I’ll post it here when I’m home.

**Comment by joshreisner** [comment]
Try this branch out. Fundamentally the problem was it was missing a line of code that reported to the app that the map didn't need to be reset every time there was a state change, but I also did a little refactoring.

Noticing some sporadic errors in the console that say `Error: @math.gl/web-mercator: assertion failed.` -- not sure what's causing it.

**Comment by FlipperPA** [comment]
@joshreisner Thanks so much for hopping in and having a look; I'll take a look at it this weekend!

**Comment by FlipperPA** [comment]
@joshreisner This is awesome, thanks for the assist. It works great. I'll merge the branch to master, do a fresh prod build, and upload.
