### ISSUE TITLE
Back / Forward Browser Navigation Doesn't Work

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#53]
As a user moves uses the application, the URL bar uses the history API to stay "bookmarkable." However navigating back and forward (using buttons on desktop browsers, swiping on mobile browsers) doesn't work, and should.

I had hoped we could simply provide listeners for `window.onpopstate` to detect back button presses and rerun getQueryString. This works with a single back button press, but doesn't seem to work beyond that and doesn't allow then going forward again. 

Probably we'll need to implement React Router, which could end up inflating our bundle size.

**Comment by joshreisner** [comment]
This is fixed now in https://github.com/code4recovery/react/commit/aaf539b1b09366eecb768538a73d3eef887ffc8f
