### ISSUE TITLE
Special Title Markers: WC / Men / Women

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#54]
Do we want to add tags next to the title for wheelchair accessibility, men only, women only? We had a request from our team.

**Comment by joshreisner** [comment]
Do you mean like little icons next to the types in the dropdown and list on the details page? 

We don't have any icons in the project yet, so my impulse is that we should add the necessary classnames so that local sites can do this on their own with CSS if they want to.

**Comment by FlipperPA** [comment]
I found a screenshot - I was referring to the ` / Men` and `/ Women`:

![image](https://user-images.githubusercontent.com/68164/73798333-7dca0900-4780-11ea-9120-ca31ae7e61a4.png)

I do like the idea of icons, however. :)

**Comment by joshreisner** [comment]
Oh right, we need those! It should be configurable in settings, with [M, W] being the default meeting types that have those little flags.

Sites that want additional types flagged (eg Open, Closed, or Wheelchair Accessible) can add override those settings.
