### ISSUE TITLE
Wide column on mobile causing horizontal scrolling

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#66]
There's a `text-nowrap` which seems to be causing horizontal scrolling on mobile:

https://github.com/code4recovery/react/blob/85adf561216b418bd9f50ec94c99e4aa32373fef/src/components/link.jsx#L32

It's partially my fault for using "Location Temporarily Closed" as a flag. Should we address this, @joshreisner? BTW, we're live! https://www.aasepia.org/

**Comment by joshreisner** [comment]
@FlipperPA that's great! 

I'm working on `TC` appearance now so hopefully that flag won't be necessary going forward, but I'll also look at removing that class. What was bothering me was that I'd frequently see a break between the `/` and the `Men` for example.

**Comment by FlipperPA** [comment]
Ah, gotcha. I've switched from `Location Temporarily Closed` to `Temp Closed` in the meantime, which looks better. Thanks again, @joshreisner :)

**Comment by joshreisner** [comment]
I took out the `text-nowrap` in the latest commit

https://github.com/code4recovery/react/commit/73040ff09636cfae2a5fcff55dc21d369048b16b
