### ISSUE TITLE
Region: display hierarchy?

### ISSUE THREAD

**Issue by FlipperPA** [code4recovery/react#68]
Right now, we're displaying the most granular region in the right hand column, such as `Rittenhouse Square` or `Ardmore`. What do you think about showing the region hierarchy? I.e.:

`Philadelphia County > Rittenhouse Square`
`Montgomery County > Ardmore`

And for sites that show specific meeting types world wide, we could then have:

`North America -> USA -> Pennsylvania -> Philadelphia`

I'm happy to take this on, if you approve!

**Comment by joshreisner** [comment]
I don't think this useful except in cases where there's ambiguity. The goal should be to keep the table as uncluttered as possible so that users can scan it quickly. I'd advise against this

**Comment by joshreisner** [comment]
… however if it's important to your area perhaps it could be a setting that is default to false, maybe `settings.defaults.full_region`

**Comment by FlipperPA** [comment]
Closing this out. It was likely just a squeaky wheel here in Philly. :)
