### ISSUE TITLE
Query String Conflicts with WordPress

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/react#71]
The query string term `day` is significant to WordPress, which is why

https://test.aasfmarin.org/meetings-test

works fine when

https://test.aasfmarin.org/meetings-test?day=2

does not.

TMSL handles this by using `tsml-day=2` but perhaps there is a better way. I'm tempted to try single letters, eg `?d=2` but several letters are reserved by WP: `m`, `p`, `w`, and `s`.

We currently have 

`day`, `region`, `time`, `type`, `mode`, `view`, `search`, and `distance`

We could do two letters? Or we could change `day` to `weekday`

**Comment by FlipperPA** [comment]
`weekday` seems good to me, and as a person who enjoys explicit URLs so I can manually hack them in the awesome bar, I prefer query strings to be decipherable! :) But that's juts me.
