### ISSUE TITLE
users struggling to find meetings due to OR search logic

### ISSUE THREAD

**Issue by leggomyinfo** [code4recovery/react#77]
Our users are having major difficulty searching for meetings ([aasfmarin.org/meetings](https://aasfmarin.org/meetings)). 

If a user is looking for one of the High Noon meetings (they meet daily), for example, they will type `High Noon`. As they type, they expect the results to progressively shrink to reflect the increasing specificity of the search terms. At first, this happens as expected — by typing `High`, the results narrow down. But then upon adding ` Noon`, the search results expand!

I understand it's possible to wrap `High Noon` in quotes to change the logic from `OR` to exact match. That is a lot to ask to users, and we now have to create a tutorial to accompany TSML to explain this. Instead, spaces should be treated as an `AND` condition, and more advanced, corner-case searching should require additional steps from users. (`AND` logic is preferable to the alternative solve of defaulting to exact match logic.)

Default `OR` logic makes sense for Google searches because:
- the potential search results are essentially infinite;
- the user doesn't necessarily know exactly what they're looking for;
- Google is using extremely advanced algorithms and an enormously comprehensive dataset on the user to return the most relevant results.

Obviously, this is different from TSML:
- the meeting finder's potential search results are finite;
- we can more or less assume anyone using search in TSML has at least some idea of what they're looking for — if they didn't, they would use the dropdown filters or map view (I realize this is not a given but, at a minimum, that reflects TSML's design since the search doesn't return results based on day, time, or type);
- TSML does not return results based on relevance (at least not relevance related to search terms) — "High Noon" is _not_ the first result when you search `High Noon`.

The other crucial difference: Google doesn't produce different results in real-time as you type. The only time Google does something like that is when auto-suggesting possible search phrases — we don't have visibility into exactly what logic goes into the suggested searches BUT the user experiences it as including `AND` logic. When a user enters search terms into the search bar, the suggested search phrases will almost always include _all_ the terms the user entered.
 
We're hoping this can get addressed quickly since this is negatively impacting the core function of TSML.

- Ideal immediate solve: spaces are treated as `AND` rather than `OR`
- Runner-up: if the ideal solve is not feasible in the immediate term, search results should reflect exact (or fuzzy) match

One other thing to note which may be relevant: quotations are also behaving unexpectedly. It's weird to enter `"Big` and get no results but receive results for `"Big"`. Perhaps over the longer-term there can be advanced search fields (like in Google). I think that should be considered as part of a holistic reconsideration of search in general, however — including "Near Location" and "Near Me" — with an emphasis on UX design.

**Comment by joshreisner** [comment]
@FlipperPA lmk your thoughts when you have a chance

**Comment by leggomyinfo** [comment]
We published a Meeting Finder FAQ page earlier today: [https://aasfmarin.org/meeting-finder-faq](https://aasfmarin.org/meeting-finder-faq). We were going to do it anyway but expedited it in response to the volume of people expressing frustration with search.

The plan is for it to be a small hyperlink in the top-right corner of [https://aasfmarin.org/meetings](https://aasfmarin.org/meetings) but Wordpress wasn't cooperating (was not enough padding from the margin and too far away from the meeting finder itself) – we've asked our web trusted servant to try to make that happen. In the meantime, it's linked in the header nav under "Find A Meeting."

**Comment by FlipperPA** [comment]
@joshreisner @leggomyinfo I can see arguments in either direction, and Fred brings up some fair points (BTW, good to see you again Fred, I think we met in Winston-Salem). Where we have found this functionality quite handy is shown in our Search Tips dialog. We had made the Search Tips dialog our default announcement when we first launched the ReactJS interface, but people have gotten used to how the search functions, so it is no longer our default selected tab:

![image](https://user-images.githubusercontent.com/68164/97083041-ab3f3700-15db-11eb-92b0-800441b998ae.png)

In the example, `devon malvern paoli "west chester"`, we show how folks can search a cluster of four towns in Philly's suburbs. Some of our users have bookmarked the resulting search on their phones for quick access to their local area. It is a nice feature. While I agree that `AND` logic would be simpler in some cases, it would be a shame to take away the precision that some of our users have gotten used to.

Maybe we could make it a configurable option, allowing web servants to choose to `AND` logic if they prefer?

**Comment by FlipperPA** [comment]
(PS: since this is one of the places in the code base I am familiar with, I'd be happy to take this on.)

**Comment by joshreisner** [comment]
ok sounds good to me, thanks @FlipperPA

**Comment by leggomyinfo** [comment]
@FlipperPA Hey Tim!

From SF/Marin's POV, that works of course; we are hurting for a solve.

Here's another option that I'm curious to get each of your reactions to: making the dropdown filters multi-select, including location. At least to a layperson such as myself, it seems like a way to significantly improve the UX without a major redesign (which I assume is out-of-reach due to resourcing constraints).

Assuming you agree that's a preferable solution and manageable to implement — BIG assumptions — would it make more sense for you to maintain something custom on your end @FlipperPA until the solve is in place instead of creating a configurable option? I worry that TSML will be more difficult to maintain and iterate on long-term if we default to configurable options rather than universal solves when possible, but I'm a bit outside my comfort zone; I don't feel confident in my take. 

To flesh out the possible solve with a few more details:
- Options within each dropdown could be clicked/tapped to select/deselect, and then you could click/tap anywhere outside the filter or the filter header itself to close the dropdown.
- Changes could populate as you make selections, as they do now.
- The labels could stay the same when the "any/all" option is selected or only one (it changes to the label selected). If more than one selected, the following states could occur: Cities (#); Days (#); Times of day (#); Types (#). The # represents the number of values selected.
- If a region is selected (county for SF), as opposed to a sub-region (city/neighborhood for SF), the # would reflect the number of subregions within that region. If the region contains 10 sub-regions and you select the region, the label would become "Cities (10)".

**Comment by leggomyinfo** [comment]
@FlipperPA If we were to run our own fork without the processSearch function reference on Line 89 https://github.com/code4recovery/react/blob/16f54aba4f2425d390fb37eeffa265fa6ee9baed/src/helpers/data.js#L89 would that get us back to the original OR logic?

Brainstorming ways we can implement an interim solve.

**Comment by FlipperPA** [comment]
Addressed in https://github.com/code4recovery/react/pull/79

**Comment by FlipperPA** [comment]
@leggomyinfo I'm going to close out this issue since we have the three options now. Thanks for the idea!
